name: Append Jira Details to PR
on: 
  pull_request:
    types: 
      - opened
jobs:
  add_jira_details:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name : Append Jira Details to PR
        uses: ./
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          jiraId: ${{ steps.get_jid.outputs.jira_id }}
          orgUrl: 'https://mock-jira-enterprise.atlassian.net'
          jiraToken: ${{ secrets.JIRA_TOKEN }}
          username: ${{ secrets.PR_USERNAME }}
          jiraKey: 'MOE,LOSIM'